name: Changelog Automation

on:
  push:
    branches:
      - master
      - release/**

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Merge')"
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Get Title PR
        id: get_message
        run: echo "::set-output name=MESSAGE::$(echo '${{github.event.head_commit.message}}' | tail -n 1)"

      - name: Update Changelog
        if: "!startsWith(github.event.head_commit.message, 'Merge')"
        uses: clicksign/changelog-action@v1.5.0
        with:
          changelog_new_log: ${{ github.event.head_commit.message }}
          log_find: '## Alterações'
          repo_main: ${{ github.ref }}
          max_logs: '8'
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
