name: Print Information

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test_output.outputs.test }}\
    steps:
      - name: Test outputs
        id: test_output
        run: |
          cat -d || true
          if [ $? == 1 ]
          then
            echo "test=failure" >> "$GITHUB_OUTPUT"
          else
            echo "test=success" >> "$GITHUB_OUTPUT"
          fi
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
