name: Print Information

on: [push, pull_request]

jobs:
  print:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false || (!startsWith(github.event.head_commit.message, 'Merge')) }}
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=BRANCH_REF::$(echo ${GITHUB_REF#refs/})"

      - name: Update Changelog
        run: echo "${{ steps.extract_branch.outputs.BRANCH_REF }}"

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
