name: Print Information

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test_output.outputs.test }}\
    steps:
      - name: Test outputs
        id: test_output
        run: |
          cat -d || \
          if [ $? == 1 ]
          then
            echo "::set-output name=test::failure"
          else
            echo "::set-output name=test::success"
          fi
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.output1 == 'failure'
    steps:
      - run: echo "error"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.output1 == 'success'
    steps:
      - run: echo "certo"
